### PR TITLE
Rest of OA2020 LLH implementation

### PR DESCRIPTION
**Pull request by jaafar-chakrani**
Here is the rest, sorry about this! :)

### CODE REVIEW

**Comment by nadrino** [comment]
Can you revert back and checkout the master?

**Comment by nadrino** [comment]
I'm doing a release, perhaps you can wait few minutes before catching up with the master branch!

**Comment by jaafar-chakrani** [comment]
Just did as you suggested, thanks again and sorry for the trouble!

**Comment by nadrino** [comment]
Don't worry!!

**Pull request merged**
