### PR TITLE
Feature: Update CMake Build

### PR DESCRIPTION
**Pull request by ClarkMcGrew**
Various changes to the CMakeLists.txt files to make the build a little more system independent.  The biggest changes are `reorganizations` to avoid changing CMAKE variables.  This also changes to using target_link_libraries for ROOT and yaml-cpp so that the libraries are added to the link command in the right order for a single pass load.  

This adds a "developer" gundam-setup.sh script and a gundam-build.sh script to simplify the command line build.  Both scripts are optional.  They combination will place the installation into a standardized system-dependent build directory.  The essential commands used for the build are

```bash
cd ${GUNDAM_BUILD}
cmake -DCMAKE_INSTALL_PREFIX=${GUNDAM_INSTALL} ${GUNDAM_SOURCE}
make
make install
```
These changes are developed on debian linux, but should be portable to any usual distribution.  They have not been tested on macos.

### CODE REVIEW

**Comment by ClarkMcGrew** [comment]
Hi Adrien,

I didn't do something like that since ```awk``` and ```sed``` are part of POSIX, and ```perl``` isn't, but... working everyplace is better than compliant, but not working.  That said, there's probably a simple reason this isn't working like expected.  

Do you know which shell MacOS is using (it's sh derived, right)?  

Also where is awk installed (I think it's usually /usr/bin/awk and /bin/sed, but I don't know what POSIX says).  We could use the direct paths.

Is it possible that there's some spurious (invisible) characters after the ```\``` line continuation?  That could create a similar error message.

**Comment by nadrino** [comment]
Yeah I agree. I remember telling me the same remark in the past for this script, because the other solutions found on the internet were not working (some were probably using the same commands awk/sed).

**Comment by nadrino** [comment]
Oh I realised I wasn't running the script with source! It's working perfectly now:
```bash
source cmake/gundam-setup.sh
```

```
Setup gundam for development and building
Source code: /Users/ablanche/Documents/Work/Repositories/clarkGundam
Build target: gundam-gcc-13.0.0-x86_64-apple-darwin21.3.0
Define GUNDAM_BUILD to change the default build area
Define GUNDAM_INSTALL to change the default installation area
Defined gundam-setup to re-setup the GUNDAM package.
Defined gundam-build to build the the GUNDAM package.
```

**Comment by nadrino** [comment]
One more thing I wanted to ask: could we remove the verbose `make` by default?
I think it's better for developpers to highlight the warnings they generate

**Comment by ClarkMcGrew** [comment]
I'm glad `gundam-setup.sh` was a simple problem!
I *like* the verbose output, but I'm just that way.  It's trivial to make it an option.  I'll follow up with a new commit in a bit (as soon as I double check that it works).

**Comment by ClarkMcGrew** [comment]
Cool!  There are still some minor cleanups and improved documentation that could go in, but that can be another PR.  Specifically, the warning options are being added in two places (as compile options and in `CMAKE_CXX_FLAGS_[DEBUG,RELEASE]`).  The release should also probably include `-g` and the debug flags should probably include `-Og`

**Comment by nadrino** [comment]
Sure! (You probably mean `-g` for debug and `-0g` for release?)
In the meanwhile I'm merging this PR :)

**Pull request merged**
